name: google_polyline_algorithm
version: 3.1.0
homepage: https://github.com/marchdev-tk/google_polyline_algorithm
description: Dart implementation of Googles Polyline Encoding lossy compression Algorithm.

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  flutter_lints: ^1.0.4
  test: ^1.20.1
