name: google_polyline_algorithm
version: 1.0.0
homepage: https://github.com/marchdev-tk/google_polyline_algorithm
description: Dart implementation of Googles Polyline Encoding lossy compression Algorithm.

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
